spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodchain?useSSL=false
    username: root
    password: root123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
# thymeleaf
  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      encoding: UTF-8
      cache: false
      servlet:
        content-type: text/html
  resources:
      chain:
        strategy:
          content:
            enabled: false
            paths: /**
  messages:
      encoding: UTF-8
      basename: config